/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';
import User from '../api/user/user.model';
import Journal from '../api/journal/journal.model';

User.find({}).remove()
  .then(() => {
    User.create({
      provider: 'local',
      name: 'Test User',
      email: 'test@example.com',
      password: 'test'
    }, {
      provider: 'local',
      role: 'admin',
      name: 'Admin',
      email: 'admin@example.com',
      password: 'admin'
    })
    .then(() => {
      console.log('finished populating users');
    });
  });

Journal.find({}).remove()
  .then(() => {
    Journal.create({
      'title': 'Manas Journal of Engineering',
      'abbreviation': 'MJEN',
      'about': {
        'gb': 'MANAS Journal of Engineering is an international peer-reviewed journal at the field of Engineering Science (Applied Math, Food, Ecology, Chemical and Computer Engineering) which aims to contribute to universal knowledge by publishing original works at a national and international level  with scientific qualifications.',
        'ru': 'MANAS журнал Engineering является международным рецензируемый журнал в области технических наук (прикладной математики, пищевой промышленности, экологии, химической и вычислительной техники), который призван способствовать обеспечению всеобщего знания путем публикации оригинальных работ на национальном и международном уровне с научной квалификации.',
        'tr': 'Mühendislik MANAS Dergisi bilimsel niteliklere sahip bir ulusal ve uluslararası düzeyde orijinal eserler yayınlayarak evrensel bilgi birikimine katkıda bulunmayı amaçlayan Mühendislik Science (Uygulamalı Matematik, Gıda, Ekoloji, Kimya ve Bilgisayar Mühendisliği) alanında uluslararası bir hakemli bir dergidir.',
        'kg': 'МАНАС инженерия эл аралык тажрыйба алмашуу каралып жатат Engineering илим тармагында боюнча журнал (Колдонмо математика, азык-түлүк, экология, химиялык жана Computer инженерия) Journal илимий талаптардын менен улуттук жана эл аралык денгээлде оригиналдуу чыгармаларын басып чыгаруу жолу менен жалпы билим салым кошууга багытталган.'
      },
      'aim-scope': {
        'gb': 'The “Manas Journal of Engineering” (MJEN) is an international online journal in English, Turkish, Kyrgyz and Russian languages published at least 2 issues per year. The aim of MJEN is to publish peer reviewed research articles, short communications and review articles in rapidly developing field of Engineering. This is an online open access journal having full access to the research and review papers. Users are allowed to read and download the articles with free of cost. The journal aims to cover the latest outstanding developments in the field of Chemical Engineering, Computer Engineering, Food Engineering, Applied Mathematics. MJEN would take much care in making your article published without much delay with your cooperation. “Manas Journal of Engineering” (MJEN) would provide a platform for budding scientists, researchers, research scholars, academicians and Industrialists etc. to present their research findings in the field of Engineering with least time loss. This journal was published by Kyrgyz-Turk Manas University, under the name of Manas Journal of Natural Sciences (Manas Fen Bilimleri Dergisi), starting in 2001. In 2013, publication was resumed under the current title, i.e. Manas Journal of Engineering (Manas Mühendislik Dergisi).',
        'ru': '"Манаса журнал Engineering" (MJEN) является международной интернет-журнал на английском, турецком, кыргызском и русском языках опубликованы по крайней мере 2 номера в год. Целью MJEN является публикация рецензируемых научных статей, краткие сообщения и обзорные статьи в быстро развивающейся области машиностроения. Это журнал онлайн открытого доступа, имеющий полный доступ к исследовательским и обзорных статей. Пользователи могут читать и скачать статьи с бесплатно. Журнал стремится охватить самые последние выдающиеся достижения в области химического машиностроения, вычислительной техники, пищевых технологий, прикладной математики. MJEN бы проявить большую заботу в создании вашей статье, опубликованной без особых задержек с вашего сотрудничества. "Манаса журнал Engineering" (MJEN) будет служить платформой для подающих надежды ученых, исследователей, ученых-исследователей, ученых и промышленников и т.д., чтобы представить результаты своих исследований в области машиностроения с наименьшими потерями времени. Этот журнал был опубликован кыргызско-Turk Манасе университета, под названием Манаса Journal естественных наук (Manas Fen Bilimleri Dergisi), начиная с 2001 г. В 2013 году издание было возобновлено под нынешнее название, т.е. Манаса журнал Engineering (Manas Mühendislik Dergisi).',
        'tr': '"Mühendislik Manas Dergisi" (MJEN) yılda en az 2 sorunları yayınlanan İngilizce, Türkçe, Kırgızca ve Rusça dillerinde uluslararası bir çevrimiçi dergidir. MJEN amacı hızla Mühendislik alanında gelişmekte olan hakemli araştırma makalesi, kısa iletişim ve yorum makalelerini yayınlamaktır. Bu araştırma ve inceleme kağıtları tam erişimi olan bir online açık erişim dergidir. Kullanıcılar okuma ve maliyet ücretsiz makaleleri indirmek için izin verilir. dergi Kimya Mühendisliği, Bilgisayar Mühendisliği, Gıda Mühendisliği, Uygulamalı Matematik alanındaki en son gelişmeleri seçkin kapsamayı amaçlamaktadır. MJEN makale işbirliği ile fazla gecikmeden yayınlanan yapımında çok dikkat ederim. "Mühendislik Manas Dergisi" (MJEN) en az zaman kaybı ile Mühendisliği alanında araştırma bulgularını tomurcuklanan bilim adamları, araştırmacılar, araştırma bilim adamları, akademisyenler ve Sanayici vb için bir platform sağlayacaktır. Bu dergi 2013 yılında 2001 yılında başlayan, Doğa Bilimleri Manas Journal (Manas Fen Bilimleri Dergisi) adı altında, Kırgız-Türk Manas Üniversitesi tarafından yayınlanan, yayın geçerli başlığı altında devam edildi, Mühendislik yani Manas Dergisi (Manas Mühendislik Dergisi).',
        'kg': '«Манас инженерия Journal» (MJEN) жылына кеминде 2 маселелерди жарыяланган англис, түрк, кыргыз жана орус тилдеринде эл аралык онлайн журнал болуп саналат. MJEN максаты курдаштардын карап илимий макалаларды, тез инженерия талааны иштеп кыска докладдарды жана макалаларды басып чыгаруу болуп саналат. Бул изилдөө жана карап чыгуу бюллетендери толук мүмкүнчүлүгү бар онлайн ачык кирүү журнал болуп саналат. Users окуп, акысыз менен макалаларды жүктөп алууга уруксат берилет. журнал Химиялык инженерия, Computer инженерия, тамак-аш инженериясы, колдонмо математика тармагында акыркы көрүнүктүү окуялар жабууга багытталган. MJEN сиздин сиздин кызматташуу менен көп токтоосуз жарыяланат кабыл алууда бир топ кам көрө турган. «Манас инженерия Journal» (MJEN) бүчүр окумуштуулар, изилдөөчүлөр, илимий-изилдөө, илимпоздор, академиктер жана өнөр аз убакыт жоготуу менен инженерия жаатында өз илимий далилдерин берүү үчүн жана башкалар үчүн шарт түзүп берүүгө болмок. Бул журнал Кыргыз-Турк Манас менен, Манас табигый илимдер журналында (Манас Табигый илимдер Dergisi) деген ат менен 2001-жылы баштап, 2013-жылы адабият азыркы аталыш менен баштады, башкача айтканда Манас инженерия Journal (Манас Mühendislik басылып чыккан Dergisi).'
      },
      'terms-conditions': {
        'gb': 'Terms and ConditionsUse of this Web Site is subject to these terms and conditions. By using this Web Site you agree to be bound by these terms and conditions which form a binding contract between you and MJEN. Individuals may view, download, print, or save Journal content for the purposes of research, teaching, and/or private study. Systematic downloading (by robots or other automatic processes) is prohibited without explicit Publisher approval.Any uses and or copies of this Journal in whole or in part must include the customary bibliographic citation, including author attribution, date, article title, MJEN Online, and the URL.Member account numbers are provided to individuals for their personal use only. Individuals may not share their username or password without the Publisher\'s permission.These terms shall be governed by and construed in accordance with Kyrgyz Rep. Law. Privacy PolicyMJEN is committed to protecting the users ’ personal information while visiting its website. Use of any part of this website will imply users’ agreement to this Privacy Policy.By registeration to the MJEN Website, submission of papers or any other information, users authorize MJEN to release their personal informationin including their identities and institutions. The personal information includes the data automatically transferred by users’ computer and/or information that users deliberately key in registration forms when they sign up as MJEN members. This information is used for verification of users’ registration and submission-publication processes. The information is archived to notify users of any news about or modifications to the MJEN Policy as well as Terms and Conditions.MJEN does not sell, rent/share any collected information to/with any Third Party. The informations may only be disclosed with users’ consent when it is necessary to comply with the lawor to protect MJEN/its users’ rights.MJEN Privacy Policy will not cover the personal information that has been collected from any third-party website. In such cases privacy policies of those websites will apply.MJEN Privacy Policy may be subject to revisions occasionally, all of which will be posted on the MJEN Website. Users are, therefore, recommended to check the website from time to time. Users’ consistent access to the website will constitute their compliance with any revisions to the MJEN Privacy Policy.',
        'ru': 'Термины и ConditionsUse данного веб-сайта в соответствии с данными условиями. С помощью этого веб-сайта вы соглашаетесь с этими условиями, которые формируют обязательный договор между вами и MJEN. Физические лица могут просматривать, загружать, печатать или сохранить содержимое журнала для целей исследований, обучения и / или частных исследований. Систематический загрузка (с помощью роботов или других автоматических процессов) запрещается без явного издателя approval.Any использует и или копии этого журнала в целом или частично должна включать в себя обычную библиографическую ссылку, в том числе автора атрибуции, дата, название статьи, MJEN онлайн, и номера URL.Member счета предоставляются физическим лицам только для их личного пользования. Лица могут не разделять их имя пользователя или пароль без permission.These терминов Издателя должны регулироваться и толковаться в соответствии с Кыргызско Rep. Законом. Конфиденциальность PolicyMJEN обязуется защищать личную информацию пользователей во время посещения его веб-сайт. Использование любой части данного веб-сайта будет означать согласие пользователей к этому конфиденциальности Policy.By Registeration к MJEN веб-сайта, представление документов или любой другой информации, пользователи санкционировать MJEN выпустить свой личный informationin включая их идентичностей и учреждений. Персональная информация включает в себя данные автоматически передаются с помощью компьютера и / или информации пользователей, которые пользователи сознательно ключевые в регистрационных формах, когда они подписывают в качестве членов MJEN. Эта информация используется для проверки регистрации и представления-публикации процессов пользователей. Информация в архиве для уведомления пользователей о каких-либо новостей о или модификации MJEN политики, а также условия и Conditions.MJEN не продает, арендует / поделиться любой собранной информации / с какой-либо третьей стороной. Эти сведения могут быть раскрыты только с согласия пользователей, когда необходимо соблюдать lawor для защиты MJEN / своих пользователей rights.MJEN Политика конфиденциальности не распространяется на личную информацию, которая была собрана из любого веб-сайта третьей стороны. В таких случаях политика конфиденциальности этих сайтов будет apply.MJEN Политика конфиденциальности может подвергаться пересмотру время от времени, все из которых будут размещены на веб-сайте MJEN. Пользователям, поэтому рекомендуется проверять веб-сайт время от времени. последовательный доступ пользователей к веб-сайт будет представлять их соответствие любых изменений к MJEN Политика конфиденциальности.',
        'tr': 'Bu Web Sitesinin Şartlar ve ConditionsUse bu hüküm ve koşullara tabidir. Bu Web Sitesini kullanarak sizin ve MJEN arasında bağlayıcı bir sözleşme oluşturacak bu hüküm ve koşullara bağlı olmayı kabul edersiniz. Bireyler, indir görüntüleyebilir, yazdırabilir, ya da araştırma, öğretim ve / veya özel çalışma amacıyla Dergisi içeriği kaydedebilirsiniz. (Robotlar veya diğer otomatik işlemlerle) Sistematik indirme açık Publisher yasaktır approval.Any kullanır ve ya tamamen ya da kısmen bu Dergisi kopyaları yazar atıf, tarih, makale başlığı, MJEN Online\'da de dahil olmak üzere geleneksel bibliyografik atıf içermelidir ve URL.Member hesap numaraları kendi kişisel kullanım için bireylere verilmektedir. Bireyler tarafından yönetilir ve Kırgız Cum. Kanuna göre tefsir edilir Yayımcı permission.These terimler olmadan kendi kullanıcı adı veya şifre paylaşamazsınız. Gizlilik PolicyMJEN kendi web sitesini ziyaret ederken kullanıcıların kişisel bilgilerini korumayı taahhüt etmektedir. Bu web sitesinin herhangi bir kısmının kullanılması MJEN Web Sitesine bu Gizlilik Policy.By registeration kullanıcıların anlaşma anlamına gelecektir, kağıt ya da diğer herhangi bir bilginin sunulması, kullanıcıların MJEN kendi kimlikleri ve kurumlar da dahil olmak üzere kendi kişisel informationin serbest bırakmak için yetki. kişisel bilgiler kayıt formlarında kasten anahtar kullanıcılar MJEN üyeleri olarak kaydolmak o zaman otomatik olarak kullanıcıların bilgisayar ve / veya bilgi ile aktarılan veri içerir. Bu bilgiler kullanıcıların kayıt ve gönderme-yayın süreçlerinin doğrulanması için kullanılır. bilgi ile ilgili herhangi bir haber kullanıcılara veya değişiklikler MJEN Politikasına yanı sıra Şartları bildirmek için arşivlenir ve Conditions.MJEN herhangi bir Üçüncü Parti ile / / kira, satmak için herhangi toplanan bilgileri paylaşmaz. bilgiler yalnızca kullanıcıların ile ifşa edilebilir \'o MJEN korumak için lawor uymak için gerekli olduğunda rıza / onun kullanıcıların herhangi bir üçüncü taraf web sitesinden toplanmıştır kişisel bilgileri kapsamaz rights.MJEN Gizlilik Politikası. Bu gibi durumlarda Gizlilik Politikası\'nı apply.MJEN olacak bu web sitelerinin gizlilik politikaları MJEN web sitesinde ilan edilecektir bütün bunlar bazen revizyonlar tabi olabilir. Kullanıcılar, bu nedenle, zaman zaman web sitesini kontrol etmek tavsiye edilir. web Kullanıcıların tutarlı erişim MJEN Gizlilik Politikası herhangi bir revizyon ile uyum teşkil edecektir.',
        'kg': 'Бул сайттан шарттары жана ConditionsUse бул шарттар жана эрежелерге баш иет. Бул сайтына колдонуу менен, Сиз менен MJEN ортосунда милдеттүү түрдө аткарылууга тийиш болгон келишим түзүшөт, бул шарттар жана эрежелерге менен макул. Жеке көрүү, жүктөп алып, басып чыгарып, же Journal изилдөө максаттары үчүн мазмун сактап кала алат, элди окутуп, жана / же жеке изилдөө. Системалуу жүктөө (робот же башка автоматтык жол менен) ачык Publisher эле тыюу салынат approval.Any колдонот толугу менен же бул журналды нускалары менен же жарым-жартылай, анын ичинде жазуучу сыпатынын кадимки Bibliographic шилтеме камтылууга тийиш, күндөн, макала аталышы, MJEN Online, жана URL.Member эсеп номерлери жеке колдонуу үчүн гана жеке адамдарга берилет. Адамдар: Chiqish permission.These шарттары алардын логинди жана паролду бөлүшүү мүмкүн эмес жөнгө жана Кыргыз Rep. Мыйзамга ылайык чечмеленүүгө тийиш. Privacy PolicyMJEN өзүнүн сайты, ал эми колдонуучулардын өздүк жеке маалыматтарын коргоо милдетин алат. Бул сайт ар кандай бөлүгүн пайдалануу MJEN сайты бул Privacy Policy.By registeration үчүн колдонуучулардын келишимди билдирет болот, документтер же ар кандай башка маалыматтарды берүүнү, колдонуучулар MJEN алардын аты-жөнүн жана мекемелерге, анын ичинде жеке informationin бошотууга уруксат. жеке маалыматты каттоо түрлөрүнө атайын негизги колдонуучулары MJEN мүчөсү катары катталып жатканда жазуусу колдонуучулардын эсептөө жана / же маалымат менен берилген маалыматтарды камтыйт. Бул маалымат колдонуучулардын каттоо жана берүү-чыгаруу жол-жоболорун текшерүү үчүн колдонулат. маалымат MJEN саясаты жөнүндө же өзгөртүүлөрдү кандайдыр бир кабар колдонуучулар, ошондой эле шарттарын кабарлоого архиделди жана Conditions.MJEN сатуу эмес, ижара / ар кандай Үчүнчү жак менен / бир чогултулган маалыматтар менен бөлүшүү. маалымат гана колдонуучулар менен ачылышы мүмкүн «, ал MJEN коргоо lawor аткаруу үчүн зарыл болгон учурда макулдугу / анын колдонуучулардын rights.MJEN Privacy Policy үчүнчү партиянын сайтынан чогултулду жеке маалымат жок. Мындай учурларда ошол сайттардын Privacy Policy apply.MJEN болот купуялык саясаты MJEN сайтында жайгаштырылат кайра кээде, анткени алар туш болушу мүмкүн эмес. Пайдалануучулар, ошондуктан, мезгил-мезгили менен сайтты текшерип сунушталат. сайт колдонуучулардын ырааттуу кирүү MJEN Купуялык саясаты кандай өзгөртүүлөр менен алардын сакталышын түзөт.'
      },
      'abstract-index': {
        'gb': 'MJEN, Manas Journal of Engineering started indexing in Google Scholar',
        'ru': 'MJEN Манаса, журнал Engineering начал индексирование в Google Scholar',
        'tr': 'MJEN, Mühendislik Manas Dergisi Google Akademik\'teki indeksleme başladı',
        'kg': 'MJEN, инженерия Манас Journal Google стипендианты индекстештирүүнү башталды'
      },
      'editorial-board': {
        'gb': 'Manas Mühendislik Bilimleri Dergisi / Manas Journal of Engineering (MJEN)Sahipleri / OwnersKırgızistan Türkiye Manas Üniversitesi AdınaProf. Dr. Sebahattin BALCIProf. Dr. Asılbek KULMIRZAYEVEditör / EditorProf. Dr. Zafer GÖNÜLALANEditör Yardımcıları / Associate EditorsYard. Doç. Dr. İlhan DOĞANYayın Kurulu / Advisory BoardProf. Dr. Ali Osman SOLAKProf. Dr. Ayhan TUTARProf. Dr. Coşkan ILICALIProf. Dr. Ulan BİRİMKULOVProf. Dr. Avıt ASANOVDoç. Dr. Tamara KARAŞOVAProf. Dr. Zarlık MAYMEKOVAlan Editörleri / Field Editors Prof. Dr. Ali Osman SOLAK (Chemistry and Chemical Engineering) Prof. Dr. Asan ÖMÜRALİYEV (Mathematics, Applied Mathematics and Informatics) Yard. Doç. Dr. İlhan DOĞAN (Biotechnology, Molecular Biology and Genetics) Doç. Dr. Raimbek SULTANOV (Computer Engineering, Information Technology)Yard. Doç. Dr. Emil OMURZAKOĞLU (Nanoscience, Nanothecnology, Nanomaterials)Yayın Sorumlusu / Editorial AssistantsRuslan ADİL AKAY TEGİNCumagül NURAKUNRedaksiyon / RedactionKırgızca : Doç. Dr.Taalaybek ABDİYEVTürkçe : : Öğr.Gör. İsmail ŞEN, Burhanettin ÇAKICIİngilizce : Öğr. Gör. Aida KASİYEVARusça : Anara BAYIZBEKOVAYayın PeriyoduYılda en az iki kez yayımlanan Manas Mühendislik Dergisi hakemli bir dergi olup yayımlanan makaleler en az iki hakem tarafından değerlendirilmektedir.Publication FrequencyManas Journal of Engineering (MJEN) is published at least twice a year, MJEN is a peer reviewed journal.Articles are evaluated by at least two reviewers.This journal was published by Kyrgyz-Turk Manas University, under the name of Fen Bilimleri Dergisi (Journal of Natural Sciences), starting in 2001. In 2013, publication was resumed under the current title, i.e. Manas Journal of Engineering (Manas Mühendislik Dergisi).Bilim Danışma Kurulu / Editorial Advisory BoardProf. Dr. Sebahattin BALCI - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Asılbek KULMIRZAYEV - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr.Ali BAHADIR - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Gülbübü KURMANBEKOVA - Kyrgyzstan-Turkey Manas University / KyrgyzistanYazışma Adresi / CorrespondenceKırgızistan Türkiye Manas Üniversitesi Mühendislik Dergisi EditörlüğüTınçtık (Mir) Caddesi No 56Bişkek KIRGIZİSTANWeb: http://journals.manas.edu.kg/mjen/index.phpMail: zgonulalan@gmail.com, journals@manas.edu.kgTel : 00996 312 492763Fax: 00996 312 541935ISSN-1694-7398',
        'ru': 'Manas Mühendislik Bilimleri Dergisi / Manas Journal of Engineering (MJEN)Sahipleri / OwnersKırgızistan Türkiye Manas Üniversitesi AdınaProf. Dr. Sebahattin BALCIProf. Dr. Asılbek KULMIRZAYEVEditör / EditorProf. Dr. Zafer GÖNÜLALANEditör Yardımcıları / Associate EditorsYard. Doç. Dr. İlhan DOĞANYayın Kurulu / Advisory BoardProf. Dr. Ali Osman SOLAKProf. Dr. Ayhan TUTARProf. Dr. Coşkan ILICALIProf. Dr. Ulan BİRİMKULOVProf. Dr. Avıt ASANOVDoç. Dr. Tamara KARAŞOVAProf. Dr. Zarlık MAYMEKOVAlan Editörleri / Field Editors Prof. Dr. Ali Osman SOLAK (Chemistry and Chemical Engineering) Prof. Dr. Asan ÖMÜRALİYEV (Mathematics, Applied Mathematics and Informatics) Yard. Doç. Dr. İlhan DOĞAN (Biotechnology, Molecular Biology and Genetics) Doç. Dr. Raimbek SULTANOV (Computer Engineering, Information Technology)Yard. Doç. Dr. Emil OMURZAKOĞLU (Nanoscience, Nanothecnology, Nanomaterials)Yayın Sorumlusu / Editorial AssistantsRuslan ADİL AKAY TEGİNCumagül NURAKUNRedaksiyon / RedactionKırgızca : Doç. Dr.Taalaybek ABDİYEVTürkçe : : Öğr.Gör. İsmail ŞEN, Burhanettin ÇAKICIİngilizce : Öğr. Gör. Aida KASİYEVARusça : Anara BAYIZBEKOVAYayın PeriyoduYılda en az iki kez yayımlanan Manas Mühendislik Dergisi hakemli bir dergi olup yayımlanan makaleler en az iki hakem tarafından değerlendirilmektedir.Publication FrequencyManas Journal of Engineering (MJEN) is published at least twice a year, MJEN is a peer reviewed journal.Articles are evaluated by at least two reviewers.This journal was published by Kyrgyz-Turk Manas University, under the name of Fen Bilimleri Dergisi (Journal of Natural Sciences), starting in 2001. In 2013, publication was resumed under the current title, i.e. Manas Journal of Engineering (Manas Mühendislik Dergisi).Bilim Danışma Kurulu / Editorial Advisory BoardProf. Dr. Sebahattin BALCI - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Asılbek KULMIRZAYEV - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr.Ali BAHADIR - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Gülbübü KURMANBEKOVA - Kyrgyzstan-Turkey Manas University / KyrgyzistanYazışma Adresi / CorrespondenceKırgızistan Türkiye Manas Üniversitesi Mühendislik Dergisi EditörlüğüTınçtık (Mir) Caddesi No 56Bişkek KIRGIZİSTANWeb: http://journals.manas.edu.kg/mjen/index.phpMail: zgonulalan@gmail.com, journals@manas.edu.kgTel : 00996 312 492763Fax: 00996 312 541935ISSN-1694-7398',
        'tr': 'Manas Mühendislik Bilimleri Dergisi / Manas Journal of Engineering (MJEN)Sahipleri / OwnersKırgızistan Türkiye Manas Üniversitesi AdınaProf. Dr. Sebahattin BALCIProf. Dr. Asılbek KULMIRZAYEVEditör / EditorProf. Dr. Zafer GÖNÜLALANEditör Yardımcıları / Associate EditorsYard. Doç. Dr. İlhan DOĞANYayın Kurulu / Advisory BoardProf. Dr. Ali Osman SOLAKProf. Dr. Ayhan TUTARProf. Dr. Coşkan ILICALIProf. Dr. Ulan BİRİMKULOVProf. Dr. Avıt ASANOVDoç. Dr. Tamara KARAŞOVAProf. Dr. Zarlık MAYMEKOVAlan Editörleri / Field Editors Prof. Dr. Ali Osman SOLAK (Chemistry and Chemical Engineering) Prof. Dr. Asan ÖMÜRALİYEV (Mathematics, Applied Mathematics and Informatics) Yard. Doç. Dr. İlhan DOĞAN (Biotechnology, Molecular Biology and Genetics) Doç. Dr. Raimbek SULTANOV (Computer Engineering, Information Technology)Yard. Doç. Dr. Emil OMURZAKOĞLU (Nanoscience, Nanothecnology, Nanomaterials)Yayın Sorumlusu / Editorial AssistantsRuslan ADİL AKAY TEGİNCumagül NURAKUNRedaksiyon / RedactionKırgızca : Doç. Dr.Taalaybek ABDİYEVTürkçe : : Öğr.Gör. İsmail ŞEN, Burhanettin ÇAKICIİngilizce : Öğr. Gör. Aida KASİYEVARusça : Anara BAYIZBEKOVAYayın PeriyoduYılda en az iki kez yayımlanan Manas Mühendislik Dergisi hakemli bir dergi olup yayımlanan makaleler en az iki hakem tarafından değerlendirilmektedir.Publication FrequencyManas Journal of Engineering (MJEN) is published at least twice a year, MJEN is a peer reviewed journal.Articles are evaluated by at least two reviewers.This journal was published by Kyrgyz-Turk Manas University, under the name of Fen Bilimleri Dergisi (Journal of Natural Sciences), starting in 2001. In 2013, publication was resumed under the current title, i.e. Manas Journal of Engineering (Manas Mühendislik Dergisi).Bilim Danışma Kurulu / Editorial Advisory BoardProf. Dr. Sebahattin BALCI - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Asılbek KULMIRZAYEV - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr.Ali BAHADIR - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Gülbübü KURMANBEKOVA - Kyrgyzstan-Turkey Manas University / KyrgyzistanYazışma Adresi / CorrespondenceKırgızistan Türkiye Manas Üniversitesi Mühendislik Dergisi EditörlüğüTınçtık (Mir) Caddesi No 56Bişkek KIRGIZİSTANWeb: http://journals.manas.edu.kg/mjen/index.phpMail: zgonulalan@gmail.com, journals@manas.edu.kgTel : 00996 312 492763Fax: 00996 312 541935ISSN-1694-7398',
        'kg': 'Manas Mühendislik Bilimleri Dergisi / Manas Journal of Engineering (MJEN)Sahipleri / OwnersKırgızistan Türkiye Manas Üniversitesi AdınaProf. Dr. Sebahattin BALCIProf. Dr. Asılbek KULMIRZAYEVEditör / EditorProf. Dr. Zafer GÖNÜLALANEditör Yardımcıları / Associate EditorsYard. Doç. Dr. İlhan DOĞANYayın Kurulu / Advisory BoardProf. Dr. Ali Osman SOLAKProf. Dr. Ayhan TUTARProf. Dr. Coşkan ILICALIProf. Dr. Ulan BİRİMKULOVProf. Dr. Avıt ASANOVDoç. Dr. Tamara KARAŞOVAProf. Dr. Zarlık MAYMEKOVAlan Editörleri / Field Editors Prof. Dr. Ali Osman SOLAK (Chemistry and Chemical Engineering) Prof. Dr. Asan ÖMÜRALİYEV (Mathematics, Applied Mathematics and Informatics) Yard. Doç. Dr. İlhan DOĞAN (Biotechnology, Molecular Biology and Genetics) Doç. Dr. Raimbek SULTANOV (Computer Engineering, Information Technology)Yard. Doç. Dr. Emil OMURZAKOĞLU (Nanoscience, Nanothecnology, Nanomaterials)Yayın Sorumlusu / Editorial AssistantsRuslan ADİL AKAY TEGİNCumagül NURAKUNRedaksiyon / RedactionKırgızca : Doç. Dr.Taalaybek ABDİYEVTürkçe : : Öğr.Gör. İsmail ŞEN, Burhanettin ÇAKICIİngilizce : Öğr. Gör. Aida KASİYEVARusça : Anara BAYIZBEKOVAYayın PeriyoduYılda en az iki kez yayımlanan Manas Mühendislik Dergisi hakemli bir dergi olup yayımlanan makaleler en az iki hakem tarafından değerlendirilmektedir.Publication FrequencyManas Journal of Engineering (MJEN) is published at least twice a year, MJEN is a peer reviewed journal.Articles are evaluated by at least two reviewers.This journal was published by Kyrgyz-Turk Manas University, under the name of Fen Bilimleri Dergisi (Journal of Natural Sciences), starting in 2001. In 2013, publication was resumed under the current title, i.e. Manas Journal of Engineering (Manas Mühendislik Dergisi).Bilim Danışma Kurulu / Editorial Advisory BoardProf. Dr. Sebahattin BALCI - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Asılbek KULMIRZAYEV - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr.Ali BAHADIR - Kyrgyzstan-Turkey Manas University / KyrgyzistanProf. Dr. Gülbübü KURMANBEKOVA - Kyrgyzstan-Turkey Manas University / KyrgyzistanYazışma Adresi / CorrespondenceKırgızistan Türkiye Manas Üniversitesi Mühendislik Dergisi EditörlüğüTınçtık (Mir) Caddesi No 56Bişkek KIRGIZİSTANWeb: http://journals.manas.edu.kg/mjen/index.phpMail: zgonulalan@gmail.com, journals@manas.edu.kgTel : 00996 312 492763Fax: 00996 312 541935ISSN-1694-7398'
      }
    }, {
      'title': 'Manas Journal of Social Studies',
      'abbreviation': 'MJSS'
    }, {
      'title': 'Manas Journal of Agriculture and Life Sciences',
      'abbreviation': 'MJAL'
    }, {
      'title': 'MANAS Journal of Economics and Administrative Science',
      'abbreviation': 'REFORMA'
    })
      .then(() => {
        console.log('finished populating journals');
      })
  });
